sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: elmt_db
    username: root
    password: abc123
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tSRxTGHoqreAEMv7XTB
    access-key-secret: RzUWjCVwa3Ll53Lm5WkIVSXT7H94dL
    bucket-name: elmt-save-oos
