sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: elmt_db
    username: root
    password: abc123
  alioss:
    endpoint: ???
    access-key-id: ???
    access-key-secret: ???
    bucket-name: ???
  redis:
    host: localhost
    port: 6379
    password: abc123
    database: 0
  wechat:
    appid: ???
    secret: ???
    mchid: ???
    mchSerialNo: ???
    privateKeyFilePath: ???
    apiV3Key: ???
    weChatPayCertFilePath: ???
    notifyUrl: ???
    refundNotifyUrl: ???
  shop:
    address: ???
  baidu:
    ak: ???
